### ISSUE TITLE
 emoji 사용시 에러메세지 unknown emoji

### ISSUE THREAD

**Issue by CGyB** [CGyB/opensource-discord-bot#9]
await msg.react(':one:');

와 같이 디스코드에 있는 이모티콘을 그대로 긁어와 이모티콘을 넣을시 

DiscordAPIError: Unknown Emoji
    at RequestHandler.execute (C:\Users\PC\Desktop\opensource\opensource-discord-bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\PC\Desktop\opensource\opensource-discord-bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async MessageManager.react (C:\Users\PC\Desktop\opensource\opensource-discord-bot\node_modules\discord.js\src\managers\MessageManager.js:198:5)
    at async Message.react (C:\Users\PC\Desktop\opensource\opensource-discord-bot\node_modules\discord.js\src\structures\Message.js:768:5)
    at async Object.execute (C:\Users\PC\Desktop\opensource\opensource-discord-bot\commands\google.js:171:9) {

다음과 같은 에러메세지가 뜸

**Comment by CGyB** [comment]
github 자동변환때문에 다르게 보이는데 실제로는 :o ne:이라는 문자열을 넣었습니다.

**Comment by CGyB** [comment]
해결법
https://www.reddit.com/r/Discord_Bots/comments/gz3rjv/get_emoji_id/fth33t4/ ( 참고 )

https://emojipedia.org/symbols/
이 사이트에 있는 형태로 긁어오면 정상작동함. 
visual studio code의 유니코드 관련 문제로 예상됩니다.
